name: Build kernel

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes binutils gcc-multilib nasm

      - name: Build kernel
        run: ./build.sh --gcc --check-headers

  build_clang:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes binutils clang nasm

      - name: Build kernel
        run: ./build.sh --clang --check-headers

